# Generated by Django 5.2.12 on 2026-04-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_retweetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweetmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='posts.postmodel'),
        ),
    ]
