# Generated by Django 5.2.12 on 2026-04-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_retweetmodel_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ["-created_at"]},
        ),
    ]
