# Generated by Django 5.2.12 on 2026-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_postmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="post_body",
            field=models.CharField(max_length=500),
        ),
    ]
