# Generated by Django 5.2.12 on 2026-04-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_postmodel_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
