# Generated by Django 5.2.12 on 2026-05-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_postmodel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.postmodel",
            ),
        ),
        migrations.DeleteModel(
            name="CommentPostModel",
        ),
    ]
