# Generated by Django 5.2.12 on 2026-05-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postmodel_parent_post_delete_commentpostmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='retweet_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='posts.postmodel'),
        ),
        migrations.DeleteModel(
            name='RetweetModel',
        ),
    ]
