# Generated by Django 5.2.12 on 2026-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postmodel_retweet_post_delete_retweetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_body',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
