# Generated by Django 6.0.3 on 2026-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("user_name", models.CharField(max_length=120, unique=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles_images/"
                    ),
                ),
                (
                    "profile_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles_banners/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("birthday", models.DateField()),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="followers", to="users.usermodel"
                    ),
                ),
            ],
        ),
    ]
