# Generated by Django 5.2.12 on 2026-04-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"ordering": ["-id"]},
        ),
    ]
