# Generated by Django 6.0.3 on 2026-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_banner",
            field=models.ImageField(
                blank=True,
                default="default_images/banner.png",
                null=True,
                upload_to="profiles_banners/",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default_images/profile.jpg",
                null=True,
                upload_to="profiles_images/",
            ),
        ),
    ]
