# Generated by Django 5.2.12 on 2026-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usermodel_profile_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="bio",
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
