# Generated by Django 5.2.12 on 2026-04-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usermodel_profile_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="profile_banner",
            field=models.ImageField(
                blank=True,
                default="default_profile_images/banner.png",
                null=True,
                upload_to="media/profile_banners/",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default_profile_images/profile.jpg",
                null=True,
                upload_to="media/profiles_images/",
            ),
        ),
    ]
